### ISSUE TITLE
Changing pins used

### ISSUE THREAD

**Issue by endoceras** [sparkfun/TMP006-Temp_Sensor_Breakout#8] opened 2015-11-13 21:07 UTC
The default code uses pins A4 and A5, Can someone please explain how to change this to pins A0 and A1? I am trying to use this temp sensor along with a gyroscope on the same arduinoUno and they're both configured to pins A4 and A5 currently.

Thanks!

**Comment by mgrusin** [comment] 2015-11-13 21:53
Hi Endoceras. The code uses pins A4 and A5 because those pins are special in that they support the I2C (also called "Wire") bus that the sensor uses to communicate with the Arduino. No other pins will work for this. The good news is that the I2C bus was designed to talk to multiple sensors attached to the same pins (as long as they have different address numbers), so you can connect both the temperature sensor and your gyroscope to A4 and A5 at the same time, and talk to both of them. I hope this helps, good luck with your project!

**Comment by ToniCorinne** [comment] 2017-02-08 00:04
Issue has been resolved for a while - closing this out.

**Closed by ToniCorinne** 2017-02-08 00:04 UTC
